<?php

namespace dnj\Invoice\Tests;

use dnj\Currency\Contracts\ICurrency;
use dnj\Currency\Contracts\ICurrencyManager;
use dnj\Currency\Contracts\RoundingBehaviour;
use dnj\Currency\CurrencyServiceProvider;
use dnj\Invoice\Contracts\IInvoiceManager;
use dnj\Invoice\Contracts\IPayment;
use dnj\Invoice\Contracts\PaymentStatus;
use dnj\Invoice\InvoiceServiceProvider;
use dnj\Invoice\Tests\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

class TestCase extends \Orchestra\Testbench\TestCase {
	use RefreshDatabase;
	
	public function setUp (): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		config()->set('invoice.user_model' , User::class);
	}
	
	protected function defineDatabaseMigrations () {
		$this->loadMigrationsFrom(__DIR__ . '/migrations');
	}
	
	protected function getPackageProviders ( $app ) {
		return [
			CurrencyServiceProvider::class ,
			InvoiceServiceProvider::class ,
		];
	}
}