<?php

namespace dnj\Invoice;

use Illuminate\Support\ServiceProvider;

class InvoiceServiceProvider extends ServiceProvider {
	public function register () {
		parent::register(); // TODO: Change the autogenerated stub
	}
	
	public function boot () {
		$this->_loadMigration();
	}
	
	private function _loadMigration () {
		$this->loadMigrationsFrom(__DIR__ . '/../database/migrations');
		$this->publishes([
							 __DIR__ . '/../database/migrations' => database_path('migrations') ,
						 ] , 'invoice-migration');
	}
}